#!/usr/bin/env php
<?php

use Illuminate\Container\Container;
use Nickfairchild\Wpise\Application;
use Nickfairchild\Wpise\Commands;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

Container::setInstance($container = new Container);

$app = new Application('Wpise', '0.1');

$app->add(new Commands\InitCommand);
$app->add(new Commands\SetupCommand);
$app->add(new Commands\SetupWordpressCommand);
$app->add(new Commands\InstallThemeCommand);
$app->add(new Commands\InstallPluginsCommand);
$app->add(new Commands\UpdateCommand);
$app->add(new Commands\EnvCommand);

$app->run();
